export const SET_LOADING = 'SET_LOADING';

export const FETCH_SNIPPETS = 'FETCH_SNIPPETS';
export const FETCH_SNIPPETS_SUCCESS = 'FETCH_SNIPPETS_SUCCESS';
export const FETCH_SNIPPETS_ERROR = 'FETCH_SNIPPETS_ERROR';
export const SET_SNIPPETS = 'SET_SNIPPETS';

export const SET_UPDATED_SNIPPET = 'SET_UPDATED_SNIPPET';
export const UPDATE_SNIPPET = 'UPDATE_SNIPPET';
export const UPDATE_SNIPPET_SUCCESS = 'UPDATE_SNIPPET_SUCCESS';
export const UPDATE_SNIPPET_ERROR = 'UPDATE_SNIPPET_ERROR';

export const CREATE_SNIPPET = 'CREATE_SNIPPET';
export const CREATE_SNIPPET_SUCCESS = 'CREATE_SNIPPET_SUCCESS';
export const CREATE_SNIPPET_ERROR = 'CREATE_SNIPPET_ERROR';

export const DELETE_SNIPPET = 'DELETE_SNIPPET';
export const DELETE_SNIPPET_SUCCESS = 'DELETE_SNIPPET_SUCCESS';
export const DELETE_SNIPPET_ERROR = 'DELETE_SNIPPET_ERROR';
